# Generated by Django 4.1.3 on 2022-11-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=180)),
                ('price_per_km', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('number_plate', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=180)),
                ('brand', models.CharField(max_length=180)),
                ('c_id', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=180)),
                ('last_name', models.CharField(max_length=180)),
                ('age', models.CharField(max_length=180)),
                ('street_no', models.CharField(max_length=180)),
                ('street', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=180)),
                ('country', models.CharField(max_length=180)),
            ],
        ),
    ]
